server:
  port: 1001


dubbo:
  application:
    #name: service-provider
    id: web-consumer
  registry:
    address: @zookeeperUrl@
    protocol: zookeeper
    check: false
  monitor:
    protocol: register
  consumer:
    check:  false
    timeout: 3000
  protocol:
    name: dubbo # java.lang.IllegalStateException: Invalid name="org.apache.dubbo.config.ApplicationConfig#0" contains illegal character, only digit, letter, '-', '_' or '.' is legal.

swagger:
  enable: true

spring:
  boot:
    admin:
      client:
        url: http://localhost:9999
        instance:
          prefer-ip: true
          #service-url: http://localhost:9999
        #username: "mqz"
        #password: "mqz"
#  security:
#    user:
#      name: "mqz"
#      password: "mqz"
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: ./logs/web/info/info.log # springbootadmin logfile显示日志的日志文件

